window.stats = {
    "Bulbasaur": {got: true},
    "Ivysaur": {got: true, candies: 0},
    "Venusaur": {got: true},
    "Charmander": {got: true, candies: 0},
    "Charmeleon": {got: true, candies: 0},
    "Charizard": {got: true},
    "Squirtle": {got: true, candies: 0},
    "Wartortle": {got: true, candies: 0},
    "Blastoise": {got: true},
    "Caterpie": {got: true, candies: 0},
    "Metapod": {got: true},
    "Butterfree": {got: true},
    "Weedle": {got: true, candies: 0},
    "Kakuna": {got: true},
    "Beedrill": {got: true},
    "Pidgey": {got: true, candies: 0},
    "Pidgeotto": {got: true},
    "Pidgeot": {got: true},
    "Rattata": {got: true, candies: 0},
    "Raticate": {got: true},
    "Spearow": {got: true, candies: 0},
    "Fearow": {got: true},
    "Ekans": {got: true, candies: 0},
    "Arbok": {got: true},
    "Pikachu": {got: true, candies: 0},
    "Raichu": {got: true},
    "Sandshrew": {got: true, candies: 0},
    "Sandslash": {got: true},
    "Nidoran (female)": {got: true, candies: 0},
    "Nidorina": {got: true, candies: 0},
    "Nidoqueen": {got: true},
    "Nidoran (male)": {got: true, candies: 0},
    "Nidorino": {got: true, candies: 0},
    "Nidoking": {got: true},
    "Clefairy": {got: true, candies: 0},
    "Clefable": {got: true},
    "Vulpix": {got: true},
    "Ninetales": {got: true},
    "Jigglypuff": {got: true, candies: 0},
    "Wigglytuff": {got: true},
    "Zubat": {got: true, candies: 0},
    "Golbat": {got: true},
    "Oddish": {got: true},
    "Gloom": {got: true, candies: 0},
    "Vileplume": {got: true},
    "Paras": {got: true, candies: 0},
    "Parasect": {got: true},
    "Venonat": {got: true, candies: 0},
    "Venomoth": {got: true},
    "Diglett": {got: true, candies: 0},
    "Dugtrio": {got: true},
    "Meowth": {got: true, candies: 0},
    "Persian": {got: true},
    "Psyduck": {got: true, candies: 0},
    "Golduck": {got: true},
    "Mankey": {got: true},
    "Primeape": {got: true},
    "Growlithe": {got: true, candies: 0},
    "Arcanine": {got: true},
    "Poliwag": {got: true, candies: 0},
    "Poliwhirl": {got: true, candies: 0},
    "Poliwrath": {got: true},
    "Abra": {got: true},
    "Kadabra": {got: true},
    "Alakazam": {got: true},
    "Machop": {got: true},
    "Machoke": {got: true},
    "Machamp": {},
    "Bellsprout": {got: true, candies: 0},
    "Weepinbell": {got: true, candies: 0},
    "Victreebel": {got: true},
    "Tentacool": {got: true, candies: 0},
    "Tentacruel": {got: true},
    "Geodude": {got: true},
    "Gravler": {got: true},
    "Golem": {},
    "Ponyta": {got: true, candies: 0},
    "Rapidash": {got: true},
    "Slowpoke": {got: true, candies: 0},
    "Slowbro": {got: true},
    "Magnemite": {got: true},
    "Magneton": {got: true},
    "Farfetch'd": {},
    "Doduo": {got: true},
    "Dodrio": {got: true},
    "Seel": {got: true},
    "Dewgong": {got: true},
    "Grimer": {got: true},
    "Muck": {got: true},
    "Shellder": {got: true, candies: 0},
    "Cloyster": {got: true},
    "Gastly": {got: true, candies: 0},
    "Haunter": {got: true},
    "Gengar": {got: true},
    "Onix": {got: true},
    "Drowzee": {got: true, candies: 0},
    "Hypno": {got: true},
    "Krabby": {got: true, candies: 0},
    "Kingler": {got: true},
    "Voltorb": {got: true},
    "Electrode": {got: true},
    "Exeggcute": {got: true, candies: 0},
    "Exeggutor": {got: true},
    "Cubone": {got: true, candies: 0},
    "Marowak": {got: true},
    "Hitmonlee": {got: true},
    "Hitmonchan": {got: true},
    "Lickitung": {got: true},
    "Koffing": {got: true, candies: 0},
    "Weezing": {got: true},
    "Rhyhorn": {got: true, candies: 0},
    "Rhydon": {got: true},
    "Chansey": {got: true},
    "Tangela": {got: true},
    "Kangaskhan": {},
    "Horsea": {got: true, candies: 0},
    "Seadra": {got: true},
    "Goldeen": {got: true},
    "Seaking": {got: true},
    "Staryu": {got: true, candies: 0},
    "Starmie": {got: true},
    "Mr. Mime": {got: true},
    "Scyther": {got: true},
    "Jynx": {got: true},
    "Electabuzz": {got: true},
    "Magmar": {got: true},
    "Pinsir": {got: true},
    "Tauros": {},
    "Magikarp": {got: true, candies: 0},
    "Gyarados": {got: true},
    "Lapras": {},
    "Ditto": {got: true},
    "Eevee": {got: true, candies: 0},
    "Vaporeon": {got: true},
    "Jolteon": {got: true},
    "Flareon": {got: true},
    "Porygon": {},
    "Omanyte": {got: true},
    "Omastar": {},
    "Kabuto": {got: true},
    "Kabutops": {},
    "Aerodactyl": {got: true},
    "Snorlax": {got: true},
    "Articuno": {},
    "Zapdos": {},
    "Moltres": {},
    "Dratini": {got: true},
    "Dragonair": {},
    "Dragonite": {},
    "Mewtwo": {},
    "Mew": {}
};
