// eslint
/* global I18N:true */

I18N._currentResources = {
	'HAND_VALUE':				'Hand value: {1}',
	'EXPECTED':					', expected: {1}',
	'INCOMPLETE':				'Incomplete Hand',

    'BAD_TILE':					'Bad Tile ({2},{1})',
    'BAMBOO':					'Bamboo',
    'CHARACTER':				'Character',
    'DOT':						'Dot',
    'DRAGON':					'Dragon',
    'WIND':						'Wind',
    'FLOWER':					'Flower',
    'SEASON':					'Season',
    'WHITE_DR':					'White Dragon',
    'GREEN_DR':					'Green Dragon',
    'RED_DR':					'Red Dragon',
    'EAST':						'East',
    'NORTH':					'North',
    'WEST':						'West',
    'SOUTH':					'South',
    'PLUM':						'Plum',
    'ORCHID':					'Orchid',
    'CHRYSANT':					'Chrysanthemum',
    'SPRING':					'Spring',
    'SUMMER':					'Summer',
    'AUTUMN':					'Autumn',
    'WINTER':					'Winter',
    'TILE_FORMAT':				'{2}-{1}',

    'UNDEFINED':				'Undefined',
    'CHOW_OF':					'Chow of {1}',
    'PUNG_OF':					'Pung of {1}',
    'KONG_OF':					'Kong of {1}',
    'PAIR_OF':					'Pair of {1}',

    'RULES_FORMAT':				'{1} points: {2}x Rule {3}: {4}',
    'RULES_FORMAT_MINI':    	'{1} points: {2}',

    'THIRTEEN_ORPHANS':				'Thirteen Orphans',
    'SEVEN_SHIFTED_PAIRS':			'Seven Shifted Pairs',
    'FOUR_KONGS':					'Four Kongs',
    'NINE_GATES':					'Nine Gates',
    'ALL_GREEN':					'All Green',
    'BIG_THREE_DRAGONS':			'Big Three Dragons',
    'BIG_FOUR_WINDS':				'Big Four Winds',
    'PURE_TERMINAL_CHOWS':			'Pure Terminal Chows',
    'FOUR_CONCEALED_PUNGS':			'Four Concealed Pungs',
    'ALL_HONORS':					'All Honors',
    'LITTLE_THREE_DRAGONS':			'Little Three Dragons',
    'LITTLE_FOUR_WINDS':			'Little Four Winds',
    'ALL_TERMINALS':				'All Terminals',
    'FOUR_PURE_SHIFTED_PUNGS':		'Four Pure Shifted Pungs',
    'PURE_QUADRUPLE_CHOW':			'Pure Quadruple Chow',
    'ALL_TERMINALS_AND_HONORS':		'All Terminals And Honors',
    'THREE_KONGS':					'Three Kongs',
    'FOUR_SHIFTED_CHOWS':			'Four Shifted Chows',
    'LOWER_TILES':					'Lower Tiles',
    'MIDDLE_TILES':					'Middle Tiles',
    'UPPER_TILES':					'Upper Tiles',
    'PURE_SHIFTED_PUNGS':			'Pure Shifted Pungs',
    'PURE_TRIPLE_CHOW':				'Pure Triple Chow',
    'FULL_FLUSH':					'Full Flush',
    'ALL_EVEN':						'All Even',
    'GREATER_HONORS_AND_KNITTED_TILES':	'Greater Honors And Knitted Tiles',
    'SEVEN_PAIRS':					'Seven Pairs',
    'THREE_CONCEALED_PUNGS':		'Three Concealed Pungs',
    'TRIPLE_PUNG':					'Triple Pung',
    'ALL_FIVES':					'All FIVES',
    'PURE_SHIFTED_CHOWS':			'Pure Shifted Chows',
    'THREE-SUITED_TERMINAL_CHOWS':	'Three Suited Terminal Chows',
    'PURE_STRAIGHT':				'Pure Straight',
    'BIG_THREE_WINDS':				'Big Three Winds',
    'LOWER_FOUR':					'Lower Four',
    'UPPER_FOUR':					'Upper Four',
    'KNITTED_STRAIGHT':				'Knitted Straight',
    'LESSER_HONORS_AND_KNITTED_TILES':	'Lesser Honors And Knitted Tiles',
    'ROBBING_THE_KONG':				'Robbing The Kong',
    'TWO_CONCEALED_KONGS':			'Two Concealed Kongs',
    'OUT_WITH_REPLACEMENT_TILE':	'Hu While Kong',
    'LAST_TILE_CLAIM':				'Last Tile Claim',
    'LAST_TILE_DRAW':				'Last Tile Draw',
    'CHICKEN_HAND':					'Chicken Hand',
    'MIXED_SHIFTED_PUNGS':			'Mixed Shifted Pungs',
    'MIXED_TRIPLE_CHOW':			'Mixed Triple Chow',
    'REVERSIBLE_TILES':				'Reversible Tiles',
    'MIXED_STRAIGHT':				'Mixed Straight',
    'ONE_MELDED_AND_ONE_CONCEALED_KONG':	'One Melded And One Concealed Kong',
    'TWO_DRAGONS':					'Two Dragons',
    'MELDED_HAND':					'Melded Hand',
    'ALL_TYPES':					'All Types',
    'MIXED_SHIFTED_CHOWS':			'Mixed Shifted Chows',
    'HALF_FLUSH':					'Half Flush',
    'ALL_PUNGS':					'All Pungs',
    'LAST_TILE':					'Last Tile',
    'TWO_MELDED_KONGS':				'Two Melded Kongs',
    'FULLY_CONCEALED_HAND':			'Fully Concealed Hand',
    'OUTSIDE_HAND':					'Outside Hand',
    'ALL_SIMPLES':					'All Simples',
    'CONCEALED_KONG':				'Concealed Kong',
    'TWO_CONCEALED_PUNGS':			'Two Concealed Pungs',
    'DOUBLE_PUNG':					'Double Pung',
    'TILE_HOG':						'Tile Hog',
    'ALL_CHOWS':					'All Chows',
    'CONCEALED_HAND':				'Concealed Hand',
    'SEAT_WIND':					'Seat Wind',
    'PREVALENT_WIND':				'Prevalent Wind',
    'DRAGON_PUNG':					'Dragon Pung',
    'FLOWER_TILES':					'Flower Tiles',
    'SELF-DRAWN':					'Self-Drawn',
    'SINGLE_WAIT':					'Single Wait',
    'CLOSED_WAIT':					'Closed Wait',
    'EDGE_WAIT':					'Edge Wait',
    'NO_HONORS':					'No Honors',
    'ONE_VOIDED_SUIT':				'One Voided Suit',
    'MELDED_KONG':					'Melded Kong',
    'PUNG_OF_TERMINALS_OR_HONORS':	'Pung Of Terminals Or Honors',
    'TWO_TERMINAL_CHOWS':			'Two Terminal Chows',
    'SHORT_STRAIGHT':				'Short Straight',
    'MIXED_DOUBLE_CHOW':			'Mixed Double Chow',
    'PURE_DOUBLE_CHOW':				'Pure Double Chow',
    'LAST_TILE_NOT_SET':			'WARNING: Last tile is not set',
    'NO_VALID_HAND':				'Not a valid special hand',

    'NO_YAKU':          			'No yaku point, this hand is not valid',

    'IPPATSU':          'Ippatsu',
    'DABURU_RIICHI':    'Daburu riichi',
    'RIICHI':           'Riichi',
    'CONCEALED_BONUS':  'Additional concealed bonus',
    'TANYAO_CHUU':      'All Simples',
    'PINFU':            'All Chows',
    'IIPEIKOU':         'Pure Double Chow',
    'JUNCHAN':          'Terminals in All Sets',
    'RYAN_PEIKOU':      'Twice Pure Double Chows',
    'TENHO':            'Blessing of Heaven',
    'CHIHO':            'Blessing of Earth',
    'RENHO':            'Blessing of Man',
    'DORA':             'Dora',
    'URADORA':          'Uradora',

    'YAKU_POINTS':      'Yaku points:',
    'YAKU':             '{1} yaku',
    'MANGAN':           'Mangan ({1} yaku)',
    'HANEMAN':          'Haneman ({1} yaku)',
    'BAIMAN':           'Baiman ({1} yaku)',
    'SANBAIMAN':        'Sanbaiman ({1} yaku)',
    'YAKUMAN':          'Yakuman ({1} yaku)',
    'DOUBLE_YAKUMAN':   'Double Yakuman ({1} yaku)',

    'MINIPOINTS':       'Minipoints:',
    'MINIPOINTS_TOTAL': '{1} Minipoints, rounded to {2}',

    'SEVEN_PAIRS_MINI': 'Seven pairs',
    'CONCEALED_ON_DISCARD': 'Concealed hand, finishing on a discard',
    'DEFAULT_MINI':     'Open hand and/or self-drawn',

    'PUNG_MINI':        'Pung of simple',
    'KONG_MINI':        'Kong of simple',
    'PUNG_HONOR_MINI':  'Pung of terminals/honors',
    'KONG_HONOR_MINI':  'Kong of terminals/honors',
    'CONCEALED_MINI':   ', concealed',

    'PAIR_DRAGON':      'Pair of dragon',
    'PAIR_TABLE_WIND':  'Pair of table wind',
    'PAIR_PLAYER_WIND': 'Pair of player wind',
    'SINGLE_WAIT_MINI': 'Single Wait',
    'CLOSED_WAIT_MINI': 'Closed Wait',
    'EDGE_WAIT_MINI':   'Edge Wait',
    'SELF_DRAWN_MINI':  'Self-Drawn',
    'OPEN_PINFU':       'Open Pinfu'
};

